export const GET_CHARACTER = 'GET_CHARACTER';
export const FETCH_LODESTONE = 'FETCH_LODESTONE';
export const FREE_COMPANY_SEARCH = 'FREE_COMPANY_SEARCH';
export const FETCH_FREE_COMPANY = 'FETCH_FREE_COMPANY';
